name: CI Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make all

  lint:
    runs-on: lint
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-tidy
        run: |
          make tidy

  sca:
    runs-on: sca
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Static Code Analysis
        run: |
          cppcheck src/ --enable=all --inconclusive --error-exitcode=1 --output-file=cppcheck.log

      - name: Upload cppcheck log
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck result
          path: cppcheck.log

  valgrind:
    runs-on: memcheck
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run valgrind
        run: |
          valgrind ./bin/myapp

  test:
    runs-on: test
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: make test
