name: CI Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make -j4 all

  lint:
    runs-on: lint
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run cpplint
        run: |
          make cpplint

  sca:
    runs-on: sca
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Static Code Analysis
        run: |
          make cppcheck

  tests-and-coverage:
    runs-on: test
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          make -j4 test_ci
          ut_res=$?
          make coverage
          cov_res=$?
          make serialization_check
          ser_res=$?
          if [[ $ut_res == 0 && $cov_res == 0 && $ser_res == 0 ]]
          then
            exit 0
          fi
          exit 1

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: unittest-results
          path: results.xml

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: |
            ./coverage_clean.info
            out/

  release:
    runs-on: release
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Build release binary
        run: |
          make release

      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: luxbot
          path: |
            ./bin/luxbot
